PixelApp/Controllers/ChatController.cs
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
using Pixel.Common.Cloud;
using PixelApp.Views.Chat;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace PixelApp.Controllers
{
    [Authorize]
    public class ChatController : BaseController
    {
        // GET: Chat
        public JsonResult Index(string since)
        {
            var chatsSince = DateTime.Now;
            if (!string.IsNullOrWhiteSpace(since))
            {
                chatsSince = DateTime.ParseExact(since, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);
                if (chatsSince < DateTime.Now.AddDays(-1))
                {
                    chatsSince = DateTime.Now.AddDays(-1);
                }
            }
            else
            {
                chatsSince = DateTime.Now.AddDays(-1);
            }

            var chatsSinceTicks = string.Format("{0:D19}", DateTime.MaxValue.Ticks - chatsSince.Ticks);

            // get chats since date
            var storageAccount = CloudStorageAccount.Parse(System.Configuration.ConfigurationManager
                .ConnectionStrings["StorageConnectionString"].ConnectionString);
            var tableClient = storageAccount.CreateCloudTableClient();
            var table = tableClient.GetTableReference(TableNames.Chats);
            table.CreateIfNotExists();

            var query = new TableQuery<ChatEntity>()
                .Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, TablePartitionKeys.GameEvents.Chats))
                .Where(TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.LessThan, chatsSinceTicks));

            var chats = table.ExecuteQuery(query)
                .OrderByDescending(x => x.RowKey)
                .Select(x => new
                {
                    Author = x.Author,
                    Message = x.Message,
                    ImageUrl = x.ImageUrl,
                    Timestamp = x.Timestamp,
                })
                .ToList();

            var chatsVm = new List<ChatViewModel>();

            foreach (var chat in chats)
            {
                var ts = DateTimeOffset.Now.Subtract(chat.Timestamp);

                chatsVm.Add(new ChatViewModel
                {
                    Author = chat.Author,
                    ImageUrl = chat.ImageUrl,
                    Message = chat.Message,
                    Posted = GetUserFriendlyTimestamp(ts),
                });
            }

            return Json(new { chats = chatsVm }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Send(ChatViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false }, JsonRequestBehavior.DenyGet);
            }

            var userId = this.User.Identity.GetUserId();
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Json(new { success = false }, JsonRequestBehavior.DenyGet);
            }

            var user = this.Context.Users.Single(x => x.Id == userId);

            var model = new ChatEntity
            {
                Author = user.UserName,
                ImageUrl = "//storageasagvk5xvrja2.blob.core.windows.net/assets/defaultprofile.png",
                Message = vm.Message,
            };

            var op = TableOperation.Insert(model);

            var storageAccount = CloudStorageAccount.Parse(System.Configuration.ConfigurationManager
                .ConnectionStrings["StorageConnectionString"].ConnectionString);
            var tableClient = storageAccount.CreateCloudTableClient();
            var table = tableClient.GetTableReference(TableNames.Chats);
            table.CreateIfNotExists();

            table.Execute(op);

            // get user friendly timestamp
            var ts = DateTimeOffset.Now.Subtract(model.Timestamp);
            var date = GetUserFriendlyTimestamp(ts);

            var chats = new List<ChatViewModel>();
            chats.Add(new ChatViewModel
            {
                Author = model.Author,
                Message = vm.Message,
                ImageUrl = model.ImageUrl,
                Posted = date,
            });

            return Json(new { success = true, chats = chats }, JsonRequestBehavior.DenyGet);
        }

        private string GetUserFriendlyTimestamp(TimeSpan ts)
        {
            //if (ts.Days == 1) // one day ago
            //    return "Yesterday";

            //if (ts.Days > 1) //  more than one day ago, but less than one week ago
            //    return ts.Days + " days ago";

            if (ts.Hours == 1) // An hour ago
                return "About an hour ago";

            if (ts.Hours > 1 && ts.Hours <= 24) // More than an hour ago, but less than a day ago
                return "About " + ts.Hours + " hours ago";

            if (ts.Minutes == 1)
                return "About a minute ago";

            if (ts.Minutes == 0)
                return ts.Seconds + " seconds ago";

            return ts.Minutes + " minutes ago";
        }
    }
}

PixelApp/Controllers/FindController.cs
using Pixel.Common.Cloud;
using Pixel.Common.Data;
using PixelApp.Models;
using PixelApp.Services;
using PixelApp.Views.Find.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PixelApp.Controllers
{
    [Authorize]
    public class FindController : BaseController
    {
        protected Random rand = new Random();

        public async Task<ActionResult> Zombies(bool hunt = false)
        {
            var vm = new FindZombiesViewModel();

            if (hunt)
            {
                if (this.UserContext.Energy < 10)
                {
                    vm.BattleText = "You don't have enough energy to hunt zombies. Wait for your energy to replenish!";
                }
                else if (this.UserContext.Life < 0)
                {
                    vm.BattleText = "You don't have any life. Zombies would surely kill you!";
                }
                else
                {
                    vm.ShowBattle = true;

                    // if win, +xp, +random res
                    // if lose, -xp, -random res
                    // if die, -xp, -more random res

                    // Calculate winPercentage
                    var offenseBoosts = this.Context.UserTechnologies.Include("Technology").Where(x => x.UserId.Equals(this.UserContext.Id)
                        && x.StatusId == UserTechnologyStatusTypes.Researched
                        && x.Technology.BoostTypeId == BoostTypes.Offense)
                        .Select(x => x.Technology.BoostAmount).ToList();
                    var winPercentage = 80 + (offenseBoosts.Sum() * 100);

                    // randomize win/lose for now
                    vm.IsWin = rand.Next(0, 100) < winPercentage; // 80% + boosts chance win

                    var deltaLife = rand.Next(0, 10) + 5;

                    // todo: seriously, the combination of updating these fields needs to go somewhere consolidated
                    this.UserContext.Life -= deltaLife;
                    this.UserContext.LifeUpdatedTime = DateTime.Now;
                    if (this.UserContext.Life <= 0)
                    {
                        vm.IsWin = false;
                        vm.IsDead = true;
                        this.UserContext.Life = 0;
                    }

                    var deltaXp = vm.IsWin ? 10 : 5;
                    this.UserContext.Experience += deltaXp * (vm.IsWin ? 1 : vm.IsDead ? -2 : -1);

                    // use energy
                    // todo: seriously, the combination of updating these fields needs to go somewhere consolidated
                    this.UserContext.Energy -= 10; // todo: config
                    this.UserContext.EnergyUpdatedTime = DateTime.Now;

                    // setup battle text for user
                    vm.BattleText = $"You lost {deltaLife} life while hunting for zombies.";

                    // todo: config
                    var percentageLoss = 0.02;
                    vm.ResourceText = ResourceService.RandomResource(this.UserContext, vm.IsWin, vm.IsDead, percentageLoss);

                    this.Context.SaveChanges();

                    var qm = new QueueManager();
                    await qm.QueueZombieFight(this.UserContext.Id, deltaXp, deltaLife, vm.IsWin, vm.IsDead);
                }
            }

            return View(vm);
        }

        public async Task<ActionResult> Food(bool forage = false)
        {
            var vm = new FindFoodViewModel();

            if (forage)
            {
                vm.HasForaged = true;
                // todo: config
                var energyRequired = 10;

                if(this.UserContext.Energy < energyRequired)
                {
                    vm.Message = "You don't have enough energy to forage for food. Wait for your energy to replenish!";
                }
                else
                {
                    this.UserContext.Energy -= energyRequired;
                    this.UserContext.EnergyUpdatedTime = DateTime.Now;

                    // 60% chance of finding food
                    if(rand.Next(0, 10) < 6)
                    {
                        // 2-5 food for now X level
                        // todo: should this be some other f(level * factor) ?

                        var level = StatManager.GetLevel(this.UserContext.Id, this.Context);

                        var qty = level * (rand.Next(0, 4) + 4);
                        vm.IsSuccess = true;
                        vm.Message = $"You spent {energyRequired} energy, and found {qty} food!";
                        var food = this.UserContext.Items.Single(x => x.ItemId == (int)ResourceTypes.Food);
                        food.Quantity += qty;

                        // todo: config
                        this.UserContext.Experience += 2;

                        this.Context.SaveChanges();

                        var qm = new QueueManager();
                        await qm.QueueFoodForage(this.UserContext.Id, 2, qty);
                    }
                    else
                    {
                        // failed to find food
                        vm.Message = $"You spent {energyRequired} energy, and didn't find any food!";
                    }
                }
            }

            return View(vm);
        }

        public ActionResult People(bool find = false)
        {
            var vm = new FindPeopleViewModel();

            if (find)
            {
                vm.HasRecruited = true;
                // todo: config
                var energyRequired = 50;

                var userEnergy = StatManager.GetEnergy(this.UserContext.Id, this.Context);

                if (userEnergy < energyRequired)
                {
                    vm.Message = "You don't have enough energy to recruit people. Wait for your energy to replenish!";
                }
                else
                {
                    this.UserContext.Energy -= energyRequired;
                    this.UserContext.EnergyUpdatedTime = DateTime.Now;

                    var cultureTechs = this.Context.UserTechnologies
                        .Include("Technology")
                        .Where(x => x.UserId.Equals(this.UserContext.Id)
                            && x.StatusId == UserTechnologyStatusTypes.Researched
                            && x.Technology.BoostTypeId == BoostTypes.Population);

                    var cultureBoost = 0.0m;

                    if (cultureTechs.Any())
                    {
                        cultureBoost = cultureTechs.Sum(x => x.Technology.BoostAmount);
                    }

                    // find random people between (level and level X 4) + culture boosts
                    var level = StatManager.GetLevel(this.UserContext.Id, this.Context);
                    var upperBound = level * 4;
                    var qty = (int)(rand.Next(level, upperBound) * (1m + cultureBoost));

                    vm.IsSuccess = true;
                    vm.Message = $"You venture into the outskirts, spending {energyRequired} energy, and you recruit {qty} people!";

                    this.UserContext.Territory.CivilianPopulation += qty;

                    // todo: config
                    this.UserContext.Experience += 5;

                    this.Context.SaveChanges();
                }
            }

            return View(vm);
        }
    }
}

PixelApp/Controllers/MapController.cs
using PixelApp.Views.Map.Models;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using PixelApp.Services;
using static PixelApp.Services.TerritoryService;
using System;

namespace PixelApp.Controllers
{
    [Authorize]
    public class MapController : BaseController
    {
        /// <summary>
        /// Map view for regular map display and optional territory selection
        /// </summary>
        /// <param name="sm">Is selection mode on?</param>
        /// <returns></returns>
        public ActionResult Index(int? size = null, string mode = null)
        {
            var vm = new MapViewModel();
            var mapOptions = new MapOptions();
            if (this.UserContext.Territory != null)
            {
                mapOptions.X = this.UserContext.Territory.X;
                mapOptions.Y = this.UserContext.Territory.Y;
                mapOptions.Size = size ?? 11;
            }
            else
            {
                var ts = new TerritoryService();
                mapOptions = ts.GetFullMapOptions();
            }

            vm = GenMapViewModel(mapOptions);
            vm.Mode = mode;
            return View(vm);
        }

        public MapViewModel GenMapViewModel(MapOptions options)
        {
            var result = new MapViewModel();
            result.X = options.X;
            result.Y = options.Y;

            var reach = (int)Math.Floor(options.Size / 2.0);
            result.Reach = reach;

            result.Territories =
            this.Context.Territories.Include(x => x.Players).Where(x =>
                x.X > (options.X - reach)
                && x.X < (options.X + reach)
                && x.Y > (options.Y - reach)
                && x.Y < (options.Y + reach)).ToList()
                .Select(x => new TerritorySkinny
                {
                    X = x.X,
                    Y = x.Y,
                    Name = x.Name,
                    UserName = x.Players.FirstOrDefault().UserName,
                    UserLevel = x.Players.FirstOrDefault().Level,
                    Type = x.Type
                }).ToList();

            return result;
        }

        public ActionResult SelectTerritory(int x, int y)
        {
            if (this.UserContext.Territory != null)
                return RedirectToAction("Index");

            var territory = TerritoryFactory.CreateTerritory(x, y);
            TerritoryFactory.InitializeTerritory(territory);
            this.Context.Territories.Add(territory);
            this.UserContext.Territory = territory;
            this.Context.SaveChanges();

            return RedirectToAction("NameTerritory", "Dashboard");
        }

        [HttpGet]
        public ActionResult AttackTerritory(int xCoord, int yCoord)
        {
            var ts = new TerritoryService();
            var vm = ts.GetTerritories().Where(x => x.X.Equals(xCoord) && x.Y.Equals(yCoord))
                .Select(x => new AttackTerritoryModel()
                    {
                        TerritoryName = x.Name,
                        UserName = x.Players.FirstOrDefault().UserName,
                        Level = x.Players.FirstOrDefault().Level,
                        TerritoryId = x.TerritoryId,
                        Population = x.CivilianPopulation,
                        TerritoryTypeId = x.Type
                    }
                ).FirstOrDefault();

            if (vm == null)
                return RedirectToAction("Index");

            return View(vm);
        }

        [HttpPost]
        public ActionResult AttackTerritory(AttackTerritoryModel vm)
        {
            var ts = new TerritoryService();
            var response = ts.AttackTerritory(this.UserContext, vm.TerritoryId);
            ts.SaveChanges();
            if (response.IsSuccessful)
            {
                vm.ResultMessages = response.Messages;
                vm.Population = ts.GetTerritories().Where(x => x.TerritoryId.Equals(vm.TerritoryId)).Select(x => x.CivilianPopulation).FirstOrDefault();
            }

            return View(vm);
        }
    }
}

PixelApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pixelocalypse</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="shortcut icon" href="/content/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/content/favicon.ico" type="image/x-icon">
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        .navbar i {
            font-size: 20px;
        }
        @@media (max-width:768px){
            .navbar {
                margin-bottom: 0;
            }
        }
        .progress-bar { 
            font-weight: bold;
        }
        .progress-bar.life {
            background-color: #d9534f;
        }
        .progress-bar.energy {
            background-color: #f0ad4e;
        }
        .table-striped > tbody > tr:nth-child(odd) > td, .table-striped > tbody > tr:nth-child(odd) > th {
            background-color: #646266;
        }
        .table-striped > tbody > tr:nth-child(even) > td, .table-striped > tbody > tr:nth-child(even) > th {
            background-color: #858186;
            color: #222123;
        }
        .main {
            background-image: url('/Content/dashboard-bg.jpg');
            background-size: cover;
            top: 0;
            bottom: 0;
        }
        .has-mail { 
            color: #d9534f !important;
        }
        .li-paypal {
            background: #d9534f;
            font-weight: bold;
        }
        .li-paypal.boosted {
            background: #5cb85c;
        }
        .li-paypal a {
            color: #fff !important;
        }
        .li-paypal a:hover {
            color: #ccc !important;
        }
        .boost-hours {
            color: #d90224;
        }
        .stop-impersonate {
            background-color: pink;
        }
        .research-progress {
            position: absolute;
            left: 0;
            top: 0;
            height: 100%;
            background-color: #060;
            z-index: -1000;
        }
        .research-progress.not-researching {
            background-color: #600;
        }

        
    </style>
</head>
<body>
    <div id="fb-root"></div>
    <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1793024100711627";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <nav class="navbar navbar-inverse sidebar" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:void(0);">Pixelocalypse</a>
                @if (ViewBag.IsImpersonating)
                {
                    @Html.ActionLink("Stop Impersonating", "StopAsync", "Impersonate", null, new { @class = "stop-impersonate"})
                }
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="vitals">
                        <strong>Name:</strong> @ViewBag.Username<br />
                        <strong>Level:</strong> @ViewBag.Level (@string.Format("{0:P0}", ViewBag.LevelProgress.ToString("0%") == "100%" ? 0.99 : ViewBag.LevelProgress))<br /><br />
                        Life: <span class="text-muted">@ViewBag.Life / @ViewBag.MaxLife</span>
                        <div class="progress">
                            <div class="progress-bar life" role="progressbar" aria-valuenow="@ViewBag.Life" aria-valuemin="0" aria-valuemax="@ViewBag.MaxLife" style="width:@ViewBag.Life%"></div>
                        </div>
                        Energy: <span class="text-muted">@ViewBag.Energy / @ViewBag.MaxEnergy</span>
                        <div class="progress">
                            <div class="progress-bar energy" role="progressbar" aria-valuenow="@ViewBag.Energy" aria-valuemin="0" aria-valuemax="@ViewBag.MaxEnergy" style="width:@ViewBag.Energy%"></div>
                        </div>
                        <div class="fb-like" data-href="http://pixelocalypse.com" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
                        <div>&nbsp;</div>
                    </li>
                    <li class="active"><a href="@Url.Action("Index", "Home")">Home<i class="pull-right hidden-xs showopacity fa fa-home"></i></a></li>
                    <li class="li-paypal @(ViewBag.BoostHours > 0 ? "boosted" : string.Empty)">
                        <a href="@Url.Action("Index", "Paypal")" data-toggle="tooltip" title="@(ViewBag.BoostHours > 0 ? "You're currently boosted, and you can always add more!" : string.Empty)">
                            Get A Boost!
                            @if (ViewBag.BoostHours > 0)
                            {
                                <small class="text-muted boost-hours">@string.Format("({0}h left!)", ViewBag.BoostHours)</small>
                            }
                            <i class="pull-right hidden-xs showopacity fa fa-thermometer-full"></i>
                        </a>
                    </li>
                    <li><a href="@Url.Action("Index", "Mailbox")" class="mailbox">Mailbox<i class="pull-right hidden-xs showopacity fa fa-envelope"></i></a></li>
                    <li><a href="@Url.Action("Index", "Map")">Map<i class="pull-right hidden-xs showopacity fa fa-globe"></i></a></li>
                    <li><a href="@Url.Action("Index", "Profile")">Profile<i class="pull-right hidden-xs showopacity fa fa-user"></i></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operations <span class="caret"></span><i class="pull-right hidden-xs showopacity fa fa-cogs"></i></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="@Url.Action("Index", "Map", new { Mode = "c"})">Attack Territories<i class="pull-right hidden-xs showopacity fa fa-shield"></i></a></li>
                            <li><a href="@Url.Action("Zombies", "Find")">Hunt Zombies<i class="pull-right hidden-xs showopacity fa fa-exclamation-triangle"></i></a></li>
                            <li><a href="@Url.Action("Food", "Find")">Find Food<i class="pull-right hidden-xs showopacity fa fa-cutlery"></i></a></li>
                            <li><a href="@Url.Action("People", "Find")">Recruit Population<i class="pull-right hidden-xs showopacity fa fa-users"></i></a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Items <span class="caret"></span><i class="pull-right hidden-xs showopacity fa fa-wrench"></i></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="@Url.Action("Index", "Trades")">Trade<i class="pull-right hidden-xs showopacity fa fa-random"></i></a></li>
                            <li><a href="@Url.Action("Index", "Inventory")">Inventory<i class="pull-right hidden-xs showopacity fa fa-th-large"></i></a></li>
                            <li><a href="@Url.Action("Index", "Workbench")">Workbench<i class="pull-right hidden-xs showopacity fa fa-briefcase"></i></a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Research")" data-toggle="tooltip"
                            title="@(ViewBag.IsResearching ? $"{ViewBag.ResearchProgress}%" : "Start resarching now!")">

                            <span style="width:@(ViewBag.IsResearching ? ViewBag.ResearchProgress : 100)%" 
                                  class="hidden-xs research-progress @(ViewBag.IsResearching ? string.Empty : "not-researching")"></span>

                            Research
                            <i class="pull-right hidden-xs showopacity fa fa-university"></i>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><i class="pull-right hidden-xs showopacity fa fa-cog"></i></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="@Url.Action("Users", "Home")">Users<i class="pull-right hidden-xs showopacity fa fa-users"></i></a></li>
                        </ul>
                    </li>
                    @if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <li><a href="javascript:signOut();">Sign Out<i class="pull-right hidden-xs showopacity fa fa-sign-out"></i></a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "signout-form" }))
    {
        @Html.AntiForgeryToken()
    }
    <div class="main">
        <!-- Content Here -->
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Pixelocalypse</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    @RenderSection("scripts", required: false)

    @Html.Partial("_Chat")

    <script type="text/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip({ html: true });
        });
    </script>

    <!-- theme setup -->
    <script type="text/javascript">
        function htmlbodyHeightUpdate() {
            var height3 = $(window).height()
            var height1 = $('.nav').height() + 50
            height2 = $('.main').height()
            if (height2 > height3) {
                $('html').height(Math.max(height1, height3, height2) + 10);
                $('body').height(Math.max(height1, height3, height2) + 10);
            }
            else {
                $('html').height(Math.max(height1, height3, height2));
                $('body').height(Math.max(height1, height3, height2));
            }

        }
        function signOut() {
            $('#signout-form').submit();
        }
        $(document).ready(function () {
            htmlbodyHeightUpdate()
            $(window).resize(function () {
                htmlbodyHeightUpdate()
            });
            $(window).scroll(function () {
                height2 = $('.main').height()
                htmlbodyHeightUpdate()
            });
        });
    </script>
    <!-- /theme setup-->

    <script type="text/javascript">
        $(function () {
            $.ajax({
                type: 'get',
                url: '/mailbox/any',
                success: function (data) {
                    if (data.hasmail) {
                        $('.mailbox').addClass('has-mail');
                    }
                }
            })
        })
    </script>
</body>
</html>